// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcDeC5tVAVpTmflLMd-3iCR-E3AB9nXCg',
    appId: '1:671903139004:web:4178649b52cfdfb6553cb9',
    messagingSenderId: '671903139004',
    projectId: 'project-akhir-75349',
    authDomain: 'project-akhir-75349.firebaseapp.com',
    storageBucket: 'project-akhir-75349.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboj1H1P25iNr4pdpyeSMnlBt9Y7cTcxs',
    appId: '1:671903139004:android:3d22b74284869d15553cb9',
    messagingSenderId: '671903139004',
    projectId: 'project-akhir-75349',
    storageBucket: 'project-akhir-75349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHAgU9DgexxMVKj7ulRWP-55WkxsFKxfA',
    appId: '1:671903139004:ios:70475b8ce286de4c553cb9',
    messagingSenderId: '671903139004',
    projectId: 'project-akhir-75349',
    storageBucket: 'project-akhir-75349.firebasestorage.app',
    iosBundleId: 'com.example.projectAkhirECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHAgU9DgexxMVKj7ulRWP-55WkxsFKxfA',
    appId: '1:671903139004:ios:70475b8ce286de4c553cb9',
    messagingSenderId: '671903139004',
    projectId: 'project-akhir-75349',
    storageBucket: 'project-akhir-75349.firebasestorage.app',
    iosBundleId: 'com.example.projectAkhirECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcDeC5tVAVpTmflLMd-3iCR-E3AB9nXCg',
    appId: '1:671903139004:web:ad96fd3dbba8e415553cb9',
    messagingSenderId: '671903139004',
    projectId: 'project-akhir-75349',
    authDomain: 'project-akhir-75349.firebaseapp.com',
    storageBucket: 'project-akhir-75349.firebasestorage.app',
  );

}